### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Healyhatman** [kylekatarnls/enhanced-period#5]
I'm almost certain I'm simply doing it wrong but the package isn't working like it's supposed to on Laravel 7.x

I'm trying to use the examples in the readme, like

```
 // Or you can directly call gap() or most of the other `Spatie\Period\Period` methods directly on `Carbon\CarbonPeriod`:
        $a = CarbonPeriod::create('2018-01-01', '2018-01-10');
        $b = CarbonPeriod::create('2018-01-15', '2018-01-31');

// It will use `Spatie\Period\Period::gap` and automatically convert the result to `Carbon\CarbonPeriod`
        echo $a->gap($b);
```
But I just get Carbon\Exceptions\UnknownMethodException : Method gap does not exist.

**Comment by kylekatarnls** [comment]
Please re-run `composer install` and check auto-discovery of enhanced-period appears in the output (after autoload regeneration).

Then you can check **vendor/composer/installed.php** (or installed.json for composer 1) to check you have
- enhanced-period >= 1.0.0
- nesbot/carbon >= 2.24.0
- spatie/period >= 2.0.0

If all the 3 are good, please also put some breakpoint/exit to check the auto-discoery that enable the mixin is ran:
https://github.com/kylekatarnls/enhanced-period/blob/master/src/EnhancedPeriod/Laravel/ServiceProvider.php#L15

**Comment by Healyhatman** [comment]
The current version of spatie/period is 1.5.3 https://github.com/spatie/period/releases
I don't appear to have an installed.* file, I do have composer.json / .lock and those things appear in there

The output after "Generating optimized autoload files" doesn't show spatie, but it does show carbon and enhanced-period

**Comment by kylekatarnls** [comment]
> The current version of spatie/period is 1.5.3

This is very old, likely `gap()` did not exist at this time (I need to check). Please upgrade first. Nothing should block from having the latest version of it there, but you might at least have the latest 1.x (1.9.0).

> I don't appear to have an installed.* file

Impossible, this is how composer works (it's inside `vendor/composer` as I said), those cannot be missing after a proper install.

> I do have composer.json / .lock and those things appear in there

composer.json is irrelevant as it contains ranges, not the precise installed version.
composer.lock can diverge from the installed package for instance if you pull a new version from your remote repository without reinstalling after.

**vendor/composer/installed.php** is the source of truth of what you're running.

> doesn't show spatie, but it does show carbon and enhanced-period

spatie does not have laravel service provider, all is fine from there.

**Comment by Healyhatman** [comment]
The current version of spatie/period on github is listed as 1.5.3, unless I'm using the wrong package?
![image](https://user-images.githubusercontent.com/13272508/108925869-79c19f80-7691-11eb-85e8-a56359308c44.png)
![image](https://user-images.githubusercontent.com/13272508/108925888-83e39e00-7691-11eb-918a-a02fb9d557ba.png)

**Comment by Healyhatman** [comment]
Sorry yes I do have an installed.php (needed to tick "Include non-project items" in PHP Storm)
```
    'spatie/period' => 
    array (
      'pretty_version' => '1.5.3',
      'version' => '1.5.3.0',
      'aliases' => 
      array (
      ),
      'reference' => '577c10ff2b803dcb9e45202d02fb4910871e63ff',
    ),
    'nesbot/carbon' => 
    array (
      'pretty_version' => '2.45.1',
      'version' => '2.45.1.0',
      'aliases' => 
      array (
      ),
      'reference' => '528783b188bdb853eb21239b1722831e0f000a8d',
    ),
    'cmixin/enhanced-period' => 
    array (
      'pretty_version' => '1.0.0',
      'version' => '1.0.0.0',
      'aliases' => 
      array (
      ),
      'reference' => 'db8a1622ce5b7e7c2a84958b41223ef3d21cb45e',
    ),
```

**Comment by kylekatarnls** [comment]
Sorry it's me I messed up with an other time related spatie package. So versions are good. I have no idea at this point.

**Comment by Healyhatman** [comment]
I put a dd(static::$macros) in CarbonPeriod.php in the hasMacro function. It gets called with $name = 'gap';

The listed macros are
```
array:4 [▼
  "toEnhancedPeriod" => Closure() {#210 ▶}
  "fromEnhancedPeriod" => Closure() {#212 ▶}
  "convertDateIntervalToPrecisionMask" => Closure() {#214 ▶}
  "convertPrecisionMaskToDateInterval" => Closure() {#216 ▶}
]
```

Those methods work, the others (gap, diff, etc) don't.

**Comment by kylekatarnls** [comment]
Thanks, that's good clue. I will investigate.

**Comment by kylekatarnls** [comment]
While checking unit tests where `->gap()` properly work, I realized PHP 8 was not yet tested and added it. So I added and had some change to make to fix compatibility.

Could you check first if those changes impacted your issue running:
```
composer require cmixin/enhanced-period:dev-master
```

To get the next release version?

Thanks 🙏

**Comment by Healyhatman** [comment]
That seems to have sorted it, it's working now. I'll hold off on rewriting my code to use the updates until you've released it. Thanks :)

**Comment by kylekatarnls** [comment]
Thanks. 1.1.0 released.
